// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsyCgXKNCaelHjIQj_lgG9IbiO1zCX79g',
    appId: '1:942301969299:web:09e9b88da82c050594c666',
    messagingSenderId: '942301969299',
    projectId: 'spotify555',
    authDomain: 'spotify555.firebaseapp.com',
    databaseURL: 'https://spotify555-default-rtdb.firebaseio.com',
    storageBucket: 'spotify555.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFyRd9pGNRpCzuS33DH0zWo1OxpiOKRa8',
    appId: '1:942301969299:android:1a533706b1ef308b94c666',
    messagingSenderId: '942301969299',
    projectId: 'spotify555',
    databaseURL: 'https://spotify555-default-rtdb.firebaseio.com',
    storageBucket: 'spotify555.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfS_eQsC8pwodlOEy8aKBT0fyKCaUNApY',
    appId: '1:942301969299:ios:a9fa14eb376994aa94c666',
    messagingSenderId: '942301969299',
    projectId: 'spotify555',
    databaseURL: 'https://spotify555-default-rtdb.firebaseio.com',
    storageBucket: 'spotify555.appspot.com',
    iosBundleId: 'com.example.datingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfS_eQsC8pwodlOEy8aKBT0fyKCaUNApY',
    appId: '1:942301969299:ios:a9fa14eb376994aa94c666',
    messagingSenderId: '942301969299',
    projectId: 'spotify555',
    databaseURL: 'https://spotify555-default-rtdb.firebaseio.com',
    storageBucket: 'spotify555.appspot.com',
    iosBundleId: 'com.example.datingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkDK8vNwGcPVqMJR4clBF_y1z_l_mUIWw',
    appId: '1:942301969299:web:ab2798a2b4e14e5894c666',
    messagingSenderId: '942301969299',
    projectId: 'spotify555',
    authDomain: 'spotify555.firebaseapp.com',
    databaseURL: 'https://spotify555-default-rtdb.firebaseio.com',
    storageBucket: 'spotify555.appspot.com',
  );
}
